package restraunt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseEvent;

public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pay = new javax.swing.JPopupMenu();
        cash = new javax.swing.JMenuItem();
        paytm = new javax.swing.JMenuItem();
        ewallet = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        invoicepane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        paybutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        calcamt = new javax.swing.JButton();
        qtypane = new javax.swing.JPanel();
        qtyminus = new javax.swing.JButton();
        qty = new javax.swing.JTextField();
        qtyplus = new javax.swing.JButton();
        qtyok = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        snacks = new javax.swing.JPanel();
        jList1 = new javax.swing.JList<>();
        jList2 = new javax.swing.JList<>();
        maincs = new javax.swing.JPanel();
        jList3 = new javax.swing.JList<>();
        jList4 = new javax.swing.JList<>();
        bread = new javax.swing.JPanel();
        jList5 = new javax.swing.JList<>();
        jList6 = new javax.swing.JList<>();
        desserts = new javax.swing.JPanel();
        jList8 = new javax.swing.JList<>();
        jList7 = new javax.swing.JList<>();
        beverages = new javax.swing.JPanel();
        jList9 = new javax.swing.JList<>();
        jList10 = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        cuisine = new javax.swing.JMenu();
        snack = new javax.swing.JMenuItem();
        mainc = new javax.swing.JMenuItem();
        breads = new javax.swing.JMenuItem();
        dessert = new javax.swing.JMenuItem();
        beverage = new javax.swing.JMenuItem();
        payment = new javax.swing.JMenu();
        ops = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        minimize = new javax.swing.JMenuItem();
        refresh = new javax.swing.JMenuItem();

        pay.setPreferredSize(new java.awt.Dimension(100, 100));

        cash.setText("Cash");
        cash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cashMousePressed(evt);
            }
        });
        pay.add(cash);

        paytm.setText("PayTm");
        paytm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paytmMousePressed(evt);
            }
        });
        pay.add(paytm);

        ewallet.setText("E-Wallet");
        ewallet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ewalletMousePressed(evt);
            }
        });
        pay.add(ewallet);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(null);

        invoicepane.setBackground(new java.awt.Color(51, 51, 51));

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTable1.setFont(new java.awt.Font("Baskerville Old Face", 0, 20)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FOOD ITEM", "RATE", "QUANTITY", "PRICE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setRowHeight(22);
        jTable1.setRowMargin(2);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INVOICE");

        paybutton.setText("PAY");
        paybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybuttonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        edit.setText("EDIT QUANTITY");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        calcamt.setText("CALCULATE AMOUNT");
        calcamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcamtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout invoicepaneLayout = new javax.swing.GroupLayout(invoicepane);
        invoicepane.setLayout(invoicepaneLayout);
        invoicepaneLayout.setHorizontalGroup(
            invoicepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicepaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(invoicepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, invoicepaneLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(calcamt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(invoicepaneLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(272, 272, 272)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, invoicepaneLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(paybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        invoicepaneLayout.setVerticalGroup(
            invoicepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicepaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(invoicepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(invoicepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit)
                    .addComponent(calcamt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paybutton)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(invoicepane);
        invoicepane.setBounds(0, 10, 850, 550);

        qtypane.setBackground(new java.awt.Color(51, 51, 51));
        qtypane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));

        qtyminus.setBackground(new java.awt.Color(51, 51, 51));
        qtyminus.setFont(new java.awt.Font("Baskerville Old Face", 0, 16)); // NOI18N
        qtyminus.setForeground(new java.awt.Color(255, 255, 255));
        qtyminus.setText("-");
        qtyminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyminusActionPerformed(evt);
            }
        });

        qty.setBackground(new java.awt.Color(51, 51, 51));
        qty.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        qty.setForeground(new java.awt.Color(255, 255, 255));
        qty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qty.setText("0");

        qtyplus.setBackground(new java.awt.Color(51, 51, 51));
        qtyplus.setFont(new java.awt.Font("Baskerville Old Face", 0, 16)); // NOI18N
        qtyplus.setForeground(new java.awt.Color(255, 255, 255));
        qtyplus.setText("+");
        qtyplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyplusActionPerformed(evt);
            }
        });

        qtyok.setBackground(new java.awt.Color(51, 51, 51));
        qtyok.setFont(new java.awt.Font("Baskerville Old Face", 0, 16)); // NOI18N
        qtyok.setForeground(new java.awt.Color(255, 255, 255));
        qtyok.setText("OK");
        qtyok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyokActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("QUANTITY");

        javax.swing.GroupLayout qtypaneLayout = new javax.swing.GroupLayout(qtypane);
        qtypane.setLayout(qtypaneLayout);
        qtypaneLayout.setHorizontalGroup(
            qtypaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qtypaneLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(qtyok, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qtypaneLayout.createSequentialGroup()
                .addGroup(qtypaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, qtypaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(qtypaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(qtyminus)
                        .addGap(18, 18, 18)
                        .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(qtyplus)))
                .addGap(17, 17, 17))
        );
        qtypaneLayout.setVerticalGroup(
            qtypaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qtypaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(qtypaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyplus)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyminus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(qtyok)
                .addContainerGap())
        );

        jPanel1.add(qtypane);
        qtypane.setBounds(0, 0, 200, 147);

        Header.setBackground(new java.awt.Color(51, 51, 51));
        Header.setForeground(new java.awt.Color(255, 255, 255));

        backbtn.setBackground(new java.awt.Color(51, 51, 51));
        backbtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        backbtn.setText("<-- GO BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ORDER WINDOW");

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DISHES");

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RATE");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(233, 233, 233))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(Header);
        Header.setBounds(20, 10, 700, 120);

        snacks.setBackground(new java.awt.Color(51, 51, 51));

        jList1.setBackground(new java.awt.Color(51, 51, 51));
        jList1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Veg Momos ", "Veg Chowmein", "Veg Spring Rolls ", "Veg Burger ", "Veg Sandwich", "Aloo Tikki ", "Chilli Potato", "Veg Chaap", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });

        jList2.setBackground(new java.awt.Color(51, 51, 51));
        jList2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jList2.setForeground(new java.awt.Color(255, 255, 255));
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Rs. 60 (8xPieces)", "Rs. 120 (Full Plate)", "Rs. 60 (10x Pieces)", "Rs. 40", "Rs. 35", "Rs. 50 (2x Pieces)", "Rs. 70 (Full Plate)", "Rs. 100 (6x Pieces)", " ", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.setEnabled(false);

        javax.swing.GroupLayout snacksLayout = new javax.swing.GroupLayout(snacks);
        snacks.setLayout(snacksLayout);
        snacksLayout.setHorizontalGroup(
            snacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(snacksLayout.createSequentialGroup()
                .addComponent(jList1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(jList2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        snacksLayout.setVerticalGroup(
            snacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(snacksLayout.createSequentialGroup()
                .addComponent(jList2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(snacksLayout.createSequentialGroup()
                .addComponent(jList1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(snacks);
        snacks.setBounds(60, 160, 579, 180);

        maincs.setBackground(new java.awt.Color(51, 51, 51));

        jList3.setBackground(new java.awt.Color(51, 51, 51));
        jList3.setFont(new java.awt.Font("Baskerville Old Face", 0, 16)); // NOI18N
        jList3.setForeground(new java.awt.Color(255, 255, 255));
        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Rs. 130 (Full Plate)", "Rs. 120 (Full Plate)", "Rs. 140 (Full Plate)", "Rs. 125 (Full Plate)", "Rs. 145 (Seasonal) (Full Plate)", "Rs. 115 (Full Plate)", "Rs. 105 (Full Plate)", "Rs. 140 (Full Plate)" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList3.setEnabled(false);

        jList4.setBackground(new java.awt.Color(51, 51, 51));
        jList4.setFont(new java.awt.Font("Baskerville Old Face", 0, 16)); // NOI18N
        jList4.setForeground(new java.awt.Color(255, 255, 255));
        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Shahi Paneer", "Dal Makhni", "Paneer Butter Masala", "Matar Paneer Mashroom", "Palak Paneer", "Dal Tadka", "Mix Veg", "Veg Manchurian", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList4.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList4ValueChanged(evt);
            }
        });

        javax.swing.GroupLayout maincsLayout = new javax.swing.GroupLayout(maincs);
        maincs.setLayout(maincsLayout);
        maincsLayout.setHorizontalGroup(
            maincsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maincsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jList4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jList3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        maincsLayout.setVerticalGroup(
            maincsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maincsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maincsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jList3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jList4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(maincs);
        maincs.setBounds(60, 360, 580, 190);

        bread.setBackground(new java.awt.Color(51, 51, 51));

        jList5.setBackground(new java.awt.Color(51, 51, 51));
        jList5.setFont(new java.awt.Font("Baskerville Old Face", 0, 16)); // NOI18N
        jList5.setForeground(new java.awt.Color(255, 255, 255));
        jList5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Tawa Butter Roti", "Tandoori  Roti", "Butter Naan", "Rumali Roti", "Lachcha Parantha", "Tandoori Poori", "Fried Rice", "Salted Rice", "Pulao", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList5.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList5.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList5ValueChanged(evt);
            }
        });

        jList6.setBackground(new java.awt.Color(51, 51, 51));
        jList6.setFont(new java.awt.Font("Baskerville Old Face", 0, 16)); // NOI18N
        jList6.setForeground(new java.awt.Color(255, 255, 255));
        jList6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Rs. 20 pp", "Rs. 25 pp", "Rs. 30 pp", "Rs. 40 pp", "Rs. 40 pp", "Rs .30 pp", "Rs. 60 (Full Plate)", "Rs. 50 (Full Plate)", "Rs. 75 (Full Plate)", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList6.setEnabled(false);

        javax.swing.GroupLayout breadLayout = new javax.swing.GroupLayout(bread);
        bread.setLayout(breadLayout);
        breadLayout.setHorizontalGroup(
            breadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(breadLayout.createSequentialGroup()
                .addComponent(jList5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jList6, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        breadLayout.setVerticalGroup(
            breadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(breadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(breadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jList6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jList5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(bread);
        bread.setBounds(60, 580, 580, 180);

        desserts.setBackground(new java.awt.Color(51, 51, 51));

        jList8.setBackground(new java.awt.Color(51, 51, 51));
        jList8.setFont(new java.awt.Font("Baskerville Old Face", 0, 16)); // NOI18N
        jList8.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Rs. 40 (2x Pieces)", "Rs. 35 (2x Pieces)", "Rs. 50 (Per Plate)", "Rs. 50 (Per Plate)", "Rs. 60 (250gm)", "Rs. 35 (per scoop(large))", "Rs. 65 ", "Rs. 80" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList8.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList8.setEnabled(false);

        jList7.setBackground(new java.awt.Color(51, 51, 51));
        jList7.setFont(new java.awt.Font("Baskerville Old Face", 0, 16)); // NOI18N
        jList7.setForeground(new java.awt.Color(255, 255, 255));
        jList7.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Gulab Jamun", "Rasgulla", "Gajar Halwa (Seasonal)", "Moong Halwa", "Jalebi", "Chocolate/Vanilla Ice-Cream", "Choco Lava Cake", "Chocolate Truffle", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList7.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList7ValueChanged(evt);
            }
        });

        javax.swing.GroupLayout dessertsLayout = new javax.swing.GroupLayout(desserts);
        desserts.setLayout(dessertsLayout);
        dessertsLayout.setHorizontalGroup(
            dessertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dessertsLayout.createSequentialGroup()
                .addComponent(jList7, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jList8, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dessertsLayout.setVerticalGroup(
            dessertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dessertsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dessertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jList7, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jList8, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(desserts);
        desserts.setBounds(60, 800, 570, 160);

        beverages.setBackground(new java.awt.Color(51, 51, 51));

        jList9.setBackground(new java.awt.Color(51, 51, 51));
        jList9.setFont(new java.awt.Font("Baskerville Old Face", 0, 16)); // NOI18N
        jList9.setForeground(new java.awt.Color(255, 255, 255));
        jList9.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Milk Shake", "Cold Coffee", "Hot Chocolate shake", "Black Coffee", "Masala Tea", "Oreo Shake", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList9.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList9.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList9ValueChanged(evt);
            }
        });

        jList10.setBackground(new java.awt.Color(51, 51, 51));
        jList10.setFont(new java.awt.Font("Baskerville Old Face", 0, 16)); // NOI18N
        jList10.setForeground(new java.awt.Color(255, 255, 255));
        jList10.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Rs. 70", "Rs. 85 (w/o ice-cream)", "Rs. 65", "Rs. 50", "Rs. 35", "Rs. 100" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList10.setEnabled(false);

        javax.swing.GroupLayout beveragesLayout = new javax.swing.GroupLayout(beverages);
        beverages.setLayout(beveragesLayout);
        beveragesLayout.setHorizontalGroup(
            beveragesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beveragesLayout.createSequentialGroup()
                .addComponent(jList9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178)
                .addComponent(jList10, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        beveragesLayout.setVerticalGroup(
            beveragesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beveragesLayout.createSequentialGroup()
                .addGroup(beveragesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jList9, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jList10, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(beverages);
        beverages.setBounds(60, 1000, 530, 140);

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N

        cuisine.setBackground(new java.awt.Color(51, 51, 51));
        cuisine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cuisine.setForeground(new java.awt.Color(0, 0, 0));
        cuisine.setText("Select Course");
        cuisine.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        cuisine.setPreferredSize(new java.awt.Dimension(141, 23));

        snack.setText("Snacks");
        snack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                snackMousePressed(evt);
            }
        });
        cuisine.add(snack);

        mainc.setText("Main Course");
        mainc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maincMousePressed(evt);
            }
        });
        cuisine.add(mainc);

        breads.setBackground(new java.awt.Color(51, 51, 51));
        breads.setForeground(new java.awt.Color(0, 0, 0));
        breads.setText("Breads");
        breads.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        breads.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                breadsMousePressed(evt);
            }
        });
        cuisine.add(breads);

        dessert.setBackground(new java.awt.Color(51, 51, 51));
        dessert.setForeground(new java.awt.Color(0, 0, 0));
        dessert.setText("Desserts");
        dessert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dessert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dessertMousePressed(evt);
            }
        });
        cuisine.add(dessert);

        beverage.setBackground(new java.awt.Color(51, 51, 51));
        beverage.setForeground(new java.awt.Color(0, 0, 0));
        beverage.setText("Beverages");
        beverage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        beverage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                beverageMousePressed(evt);
            }
        });
        cuisine.add(beverage);

        jMenuBar1.add(cuisine);

        payment.setBackground(new java.awt.Color(51, 51, 51));
        payment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        payment.setForeground(new java.awt.Color(0, 0, 0));
        payment.setText("Proceed to Payment");
        payment.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        payment.setPreferredSize(new java.awt.Dimension(195, 23));
        payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paymentMousePressed(evt);
            }
        });
        jMenuBar1.add(payment);

        ops.setBackground(new java.awt.Color(51, 51, 51));
        ops.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ops.setForeground(new java.awt.Color(0, 0, 0));
        ops.setText("Options");
        ops.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        ops.setPreferredSize(new java.awt.Dimension(89, 23));

        exit.setText("Close");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        ops.add(exit);

        minimize.setText("Minimize");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimizeMousePressed(evt);
            }
        });
        ops.add(minimize);

        refresh.setText("Refresh");
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                refreshMousePressed(evt);
            }
        });
        ops.add(refresh);

        jMenuBar1.add(ops);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1176, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paymentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentMousePressed
invoicepane.setVisible(true);
invoicepane.setBounds(40,40,846, 514);
Header.setVisible(false);
    }//GEN-LAST:event_paymentMousePressed

    private void cashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashMousePressed
Payment_Cash pycsh=new Payment_Cash();
pycsh.setVisible(true);
pycsh.pack();
pycsh.setLocationRelativeTo(null);
pycsh.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
pay.setVisible(false);
    }//GEN-LAST:event_cashMousePressed

    private void paytmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paytmMousePressed
Payment_PayTm pyptm=new Payment_PayTm();
pyptm.setVisible(true);
pyptm.pack();
pyptm.setLocationRelativeTo(null);
pyptm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
pay.setVisible(false);
    }//GEN-LAST:event_paytmMousePressed

    private void ewalletMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ewalletMousePressed
Payment_Ewallet pyew=new Payment_Ewallet();
pyew.setVisible(true);
pyew.pack();
pyew.setLocationRelativeTo(null);
pyew.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
pay.setVisible(false);
    }//GEN-LAST:event_ewalletMousePressed

    private void refreshMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMousePressed
this.repaint();
jList1.setSelectedIndex(-1);
jList4.setSelectedIndex(-1);
jList5.setSelectedIndex(-1);
jList7.setSelectedIndex(-1);
jList9.setSelectedIndex(-1);
    }//GEN-LAST:event_refreshMousePressed

    private void minimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMousePressed
this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMousePressed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
System.exit(1);
    }//GEN-LAST:event_exitMousePressed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
Home hm=new Home();
hm.setVisible(true);
hm.pack();
hm.setLocationRelativeTo(null);
hm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
this.setLocationRelativeTo(null);
snacks.setVisible(false);
maincs.setVisible(false);
bread.setVisible(false);
desserts.setVisible(false);
beverages.setVisible(false);
qtypane.setVisible(false);
invoicepane.setVisible(false);
paybutton.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void snackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_snackMousePressed
snacks.setVisible(true);snacks.setBounds(54,165,579,222);
maincs.setVisible(false);
bread.setVisible(false);
desserts.setVisible(false);
beverages.setVisible(false);
    }//GEN-LAST:event_snackMousePressed

    private void maincMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maincMousePressed
snacks.setVisible(false);
maincs.setVisible(true);maincs.setBounds(54,165,579,222);
bread.setVisible(false);
desserts.setVisible(false);
beverages.setVisible(false);
    }//GEN-LAST:event_maincMousePressed

    private void breadsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_breadsMousePressed
snacks.setVisible(false);
maincs.setVisible(false);
bread.setVisible(true);bread.setBounds(54,165,579,222);
desserts.setVisible(false);
beverages.setVisible(false);
    }//GEN-LAST:event_breadsMousePressed

    private void dessertMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dessertMousePressed
snacks.setVisible(false);
maincs.setVisible(false);
bread.setVisible(false);
desserts.setVisible(true);desserts.setBounds(54,165,579,222);
beverages.setVisible(false);      
    }//GEN-LAST:event_dessertMousePressed

    private void beverageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beverageMousePressed
snacks.setVisible(false);
maincs.setVisible(false);
bread.setVisible(false);
desserts.setVisible(false);
beverages.setVisible(true);beverages.setBounds(54,165,579,222);  
    }//GEN-LAST:event_beverageMousePressed
public String item; public int rateprice;
    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
ResultSet rs; item=jList1.getSelectedValue();
try
    {
        Class.forName("java.sql.DriverManager");
        Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pekaiser","root","pallav0309");
        Statement s1=(Statement)con.createStatement();
        rs=s1.executeQuery("select rate from menu where dish='"+jList1.getSelectedValue().trim()+"'; ");   
        if(rs.next())
            {
                rateprice=rs.getInt("rate");
            }
    }
catch(Exception er)
    {
        JOptionPane.showMessageDialog(null,er);
    }        

qtypane.setVisible(true);
qtypane.setLocation(300,200);
qty.setText(0+"");
    }//GEN-LAST:event_jList1ValueChanged

    private void qtyplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyplusActionPerformed
qty.setText((Integer.parseInt(qty.getText())+1)+"");
if(Integer.parseInt(qty.getText())>10)
{
    qty.setText(10+"");
    JOptionPane.showMessageDialog(null,"Maximum limit of 8 items per order");
}
    }//GEN-LAST:event_qtyplusActionPerformed

    private void qtyminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyminusActionPerformed
qty.setText((Integer.parseInt(qty.getText())-1)+"");
if(Integer.parseInt(qty.getText())<0)
    qty.setText(0+"");    
    }//GEN-LAST:event_qtyminusActionPerformed

public int qnty;

    private void qtyokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyokActionPerformed
qnty=Integer.parseInt(qty.getText());
qtypane.setVisible(false);
DefaultTableModel tm=(DefaultTableModel)jTable1.getModel(); 
int price=rateprice*qnty;
tm.addRow(new Object[] {item,rateprice,qnty,price});
    }//GEN-LAST:event_qtyokActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
pay.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void paybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybuttonActionPerformed
pay.setVisible(true);
pay.setLocation(506,38);
cash.setText("Cash");
paytm.setText("PayTm");
ewallet.setText("E-Wallet");
    }//GEN-LAST:event_paybuttonActionPerformed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
invoicepane.setVisible(false);Header.setVisible(true);
    }//GEN-LAST:event_jLabel5MousePressed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
//to enable an option to edit the quantity
    }//GEN-LAST:event_editActionPerformed

    private void calcamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcamtActionPerformed
int amt=0;
for(int i = 0; i < jTable1.getRowCount(); i++)
    amt+= (int) jTable1.getValueAt(i,3);
paybutton.setVisible(true);
paybutton.setText("PAY"+" "+amt);
    }//GEN-LAST:event_calcamtActionPerformed

    private void jList5ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList5ValueChanged
ResultSet rs; item=jList5.getSelectedValue();
try
    {
        Class.forName("java.sql.DriverManager");
        Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pekaiser","root","pallav0309");
        Statement s1=(Statement)con.createStatement();
        rs=s1.executeQuery("select rate from menu where dish='"+jList5.getSelectedValue().trim()+"'; ");   
        if(rs.next())
            {
                rateprice=rs.getInt("rate");
            }
    }
catch(Exception er)
    {
        JOptionPane.showMessageDialog(null,er);
    }        

qtypane.setVisible(true);
qtypane.setLocation(300,200);
qty.setText(0+"");    
    }//GEN-LAST:event_jList5ValueChanged

    private void jList7ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList7ValueChanged
ResultSet rs; item=jList7.getSelectedValue();
try
    {
        Class.forName("java.sql.DriverManager");
        Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pekaiser","root","pallav0309");
        Statement s1=(Statement)con.createStatement();
        rs=s1.executeQuery("select rate from menu where dish='"+jList7.getSelectedValue().trim()+"'; ");   
        if(rs.next())
            {
                rateprice=rs.getInt("rate");
            }
    }
catch(Exception er)
    {
        JOptionPane.showMessageDialog(null,er);
    }        

qtypane.setVisible(true);
qtypane.setLocation(300,200);
qty.setText(0+"");
    }//GEN-LAST:event_jList7ValueChanged

    private void jList4ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList4ValueChanged
ResultSet rs; item=jList4.getSelectedValue();
try
    {
        Class.forName("java.sql.DriverManager");
        Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pekaiser","root","pallav0309");
        Statement s1=(Statement)con.createStatement();
        rs=s1.executeQuery("select rate from menu where dish='"+jList4.getSelectedValue().trim()+"'; ");   
        if(rs.next())
            {
                rateprice=rs.getInt("rate");
            }
    }
catch(Exception er)
    {
        JOptionPane.showMessageDialog(null,er);
    }        

qtypane.setVisible(true);
qtypane.setLocation(300,200);
qty.setText(0+"");
    }//GEN-LAST:event_jList4ValueChanged

    private void jList9ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList9ValueChanged
ResultSet rs; item=jList9.getSelectedValue();
try
    {
        Class.forName("java.sql.DriverManager");
        Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/pekaiser","root","pallav0309");
        Statement s1=(Statement)con.createStatement();
        rs=s1.executeQuery("select rate from menu where dish='"+jList9.getSelectedValue().trim()+"'; ");   
        if(rs.next())
            {
                rateprice=rs.getInt("rate");
            }
    }
catch(Exception er)
    {
        JOptionPane.showMessageDialog(null,er);
    }        

qtypane.setVisible(true);
qtypane.setLocation(300,200);
qty.setText(0+"");
    }//GEN-LAST:event_jList9ValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JButton backbtn;
    private javax.swing.JMenuItem beverage;
    private javax.swing.JPanel beverages;
    private javax.swing.JPanel bread;
    private javax.swing.JMenuItem breads;
    private javax.swing.JButton calcamt;
    private javax.swing.JMenuItem cash;
    private javax.swing.JMenu cuisine;
    private javax.swing.JMenuItem dessert;
    private javax.swing.JPanel desserts;
    private javax.swing.JButton edit;
    private javax.swing.JMenuItem ewallet;
    private javax.swing.JMenuItem exit;
    private javax.swing.JPanel invoicepane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList10;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList6;
    private javax.swing.JList<String> jList7;
    private javax.swing.JList<String> jList8;
    private javax.swing.JList<String> jList9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem mainc;
    private javax.swing.JPanel maincs;
    private javax.swing.JMenuItem minimize;
    private javax.swing.JMenu ops;
    private javax.swing.JPopupMenu pay;
    private javax.swing.JButton paybutton;
    private javax.swing.JMenu payment;
    private javax.swing.JMenuItem paytm;
    private javax.swing.JTextField qty;
    private javax.swing.JButton qtyminus;
    private javax.swing.JButton qtyok;
    private javax.swing.JPanel qtypane;
    private javax.swing.JButton qtyplus;
    private javax.swing.JMenuItem refresh;
    private javax.swing.JMenuItem snack;
    private javax.swing.JPanel snacks;
    // End of variables declaration//GEN-END:variables
}
